name: Run Pytest on Push

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install pip-tools
      run: python -m pip install -U pip-tools
      
    - name: Generate requirements.txt
      run: pip-compile requirements.in
      
    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Install package
      run: python -m pip install .

    - name: Run pytest
      run: pytest tests
